export interface Abonado {
    id?: string,
    identificador?: number,
    descripcion?: string,
    cel?: string,
    fecha?: string,
    pon?: string,
    pagoEnero?: string,
    pagoFebrero?: string,
    pagoMarzo?: string,
    pagoAbril?: string,
    pagoMayo?: string,
    pagoJunio?: string,
    pagoJulio?: string,
    pagoAgosto?: string,
    pagoSeptiembre?: string,
    pagoOctubre?: string,
    pagoNoviembre?: string,
    pagoDiciembre?: string,
}
